<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use UnexpectedValueException;

/**
 * Protobuf type <code>kuaishouPubf.AssistantType</code>
 */
class AssistantType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ASSISTANT_TYPE = 0;</code>
     */
    const UNKNOWN_ASSISTANT_TYPE = 0;
    /**
     * Generated from protobuf enum <code>ASSISTANT_SUPER = 1;</code>
     */
    const ASSISTANT_SUPER = 1;
    /**
     * Generated from protobuf enum <code>ASSISTANT_JUNIOR = 2;</code>
     */
    const ASSISTANT_JUNIOR = 2;

    private static $valueToName = [
        self::UNKNOWN_ASSISTANT_TYPE => 'UNKNOWN_ASSISTANT_TYPE',
        self::ASSISTANT_SUPER => 'ASSISTANT_SUPER',
        self::ASSISTANT_JUNIOR => 'ASSISTANT_JUNIOR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

