<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

if (false) {
    /**
     * This class is deprecated. Use KuaishouPubf\CSWebEnterRoom\Payload instead.
     * @deprecated
     */
    class CSWebEnterRoom_Payload {}
}
class_exists(CSWebEnterRoom\Payload::class);
@trigger_error('KuaishouPubf\CSWebEnterRoom_Payload is deprecated and will be removed in the next major release. Use KuaishouPubf\CSWebEnterRoom\Payload instead', E_USER_DEPRECATED);

