<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

if (false) {
    /**
     * This class is deprecated. Use KuaishouPubf\CSWebHeartbeat\Payload instead.
     * @deprecated
     */
    class CSWebHeartbeat_Payload {}
}
class_exists(CSWebHeartbeat\Payload::class);
@trigger_error('KuaishouPubf\CSWebHeartbeat_Payload is deprecated and will be removed in the next major release. Use KuaishouPubf\CSWebHeartbeat\Payload instead', E_USER_DEPRECATED);

