<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 进入房间
 *
 * Generated from protobuf message <code>kuaishouPubf.CSWebEnterRoom</code>
 */
class CSWebEnterRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Generated from protobuf field <code>.kuaishouPubf.CSWebEnterRoom.Payload payload = 3;</code>
     */
    protected $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $payloadType
     *     @type \KuaishouPubf\CSWebEnterRoom\Payload $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 payloadType = 1;</code>
     * @return int|string
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>int64 payloadType = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkInt64($var);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.CSWebEnterRoom.Payload payload = 3;</code>
     * @return \KuaishouPubf\CSWebEnterRoom\Payload|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.CSWebEnterRoom.Payload payload = 3;</code>
     * @param \KuaishouPubf\CSWebEnterRoom\Payload $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \KuaishouPubf\CSWebEnterRoom\Payload::class);
        $this->payload = $var;

        return $this;
    }

}

