<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 心跳包响应
 *
 * Generated from protobuf message <code>kuaishouPubf.SCHeartbeatAck</code>
 */
class SCHeartbeatAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>uint64 clientTimestamp = 2;</code>
     */
    protected $clientTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type int|string $clientTimestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 clientTimestamp = 2;</code>
     * @return int|string
     */
    public function getClientTimestamp()
    {
        return $this->clientTimestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 clientTimestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->clientTimestamp = $var;

        return $this;
    }

}

