<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 进入房间后应答包
 *
 * Generated from protobuf message <code>kuaishouPubf.SCWebEnterRoomAck</code>
 */
class SCWebEnterRoomAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 minReconnectMs = 1;</code>
     */
    protected $minReconnectMs = 0;
    /**
     * Generated from protobuf field <code>uint64 maxReconnectMs = 2;</code>
     */
    protected $maxReconnectMs = 0;
    /**
     * Generated from protobuf field <code>uint64 heartbeatIntervalMs = 3;</code>
     */
    protected $heartbeatIntervalMs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $minReconnectMs
     *     @type int|string $maxReconnectMs
     *     @type int|string $heartbeatIntervalMs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 minReconnectMs = 1;</code>
     * @return int|string
     */
    public function getMinReconnectMs()
    {
        return $this->minReconnectMs;
    }

    /**
     * Generated from protobuf field <code>uint64 minReconnectMs = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinReconnectMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->minReconnectMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 maxReconnectMs = 2;</code>
     * @return int|string
     */
    public function getMaxReconnectMs()
    {
        return $this->maxReconnectMs;
    }

    /**
     * Generated from protobuf field <code>uint64 maxReconnectMs = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxReconnectMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->maxReconnectMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 heartbeatIntervalMs = 3;</code>
     * @return int|string
     */
    public function getHeartbeatIntervalMs()
    {
        return $this->heartbeatIntervalMs;
    }

    /**
     * Generated from protobuf field <code>uint64 heartbeatIntervalMs = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeartbeatIntervalMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->heartbeatIntervalMs = $var;

        return $this;
    }

}

