<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 观看用户数
 *
 * Generated from protobuf message <code>kuaishouPubf.SCWebLiveWatchingUsers</code>
 */
class SCWebLiveWatchingUsers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .kuaishouPubf.WebWatchingUserInfo watchingUser = 1;</code>
     */
    private $watchingUser;
    /**
     * Generated from protobuf field <code>string displayWatchingCount = 2;</code>
     */
    protected $displayWatchingCount = '';
    /**
     * Generated from protobuf field <code>uint64 pendingDuration = 3;</code>
     */
    protected $pendingDuration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\KuaishouPubf\WebWatchingUserInfo>|\Google\Protobuf\Internal\RepeatedField $watchingUser
     *     @type string $displayWatchingCount
     *     @type int|string $pendingDuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .kuaishouPubf.WebWatchingUserInfo watchingUser = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWatchingUser()
    {
        return $this->watchingUser;
    }

    /**
     * Generated from protobuf field <code>repeated .kuaishouPubf.WebWatchingUserInfo watchingUser = 1;</code>
     * @param array<\KuaishouPubf\WebWatchingUserInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWatchingUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \KuaishouPubf\WebWatchingUserInfo::class);
        $this->watchingUser = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string displayWatchingCount = 2;</code>
     * @return string
     */
    public function getDisplayWatchingCount()
    {
        return $this->displayWatchingCount;
    }

    /**
     * Generated from protobuf field <code>string displayWatchingCount = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayWatchingCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayWatchingCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pendingDuration = 3;</code>
     * @return int|string
     */
    public function getPendingDuration()
    {
        return $this->pendingDuration;
    }

    /**
     * Generated from protobuf field <code>uint64 pendingDuration = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPendingDuration($var)
    {
        GPBUtil::checkUint64($var);
        $this->pendingDuration = $var;

        return $this;
    }

}

