<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use UnexpectedValueException;

/**
 * Protobuf type <code>kuaishouPubf.StyleType</code>
 */
class StyleType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_STYLE = 0;</code>
     */
    const UNKNOWN_STYLE = 0;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_0 = 1;</code>
     */
    const BATCH_STAR_0 = 1;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_1 = 2;</code>
     */
    const BATCH_STAR_1 = 2;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_2 = 3;</code>
     */
    const BATCH_STAR_2 = 3;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_3 = 4;</code>
     */
    const BATCH_STAR_3 = 4;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_4 = 5;</code>
     */
    const BATCH_STAR_4 = 5;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_5 = 6;</code>
     */
    const BATCH_STAR_5 = 6;
    /**
     * Generated from protobuf enum <code>BATCH_STAR_6 = 7;</code>
     */
    const BATCH_STAR_6 = 7;

    private static $valueToName = [
        self::UNKNOWN_STYLE => 'UNKNOWN_STYLE',
        self::BATCH_STAR_0 => 'BATCH_STAR_0',
        self::BATCH_STAR_1 => 'BATCH_STAR_1',
        self::BATCH_STAR_2 => 'BATCH_STAR_2',
        self::BATCH_STAR_3 => 'BATCH_STAR_3',
        self::BATCH_STAR_4 => 'BATCH_STAR_4',
        self::BATCH_STAR_5 => 'BATCH_STAR_5',
        self::BATCH_STAR_6 => 'BATCH_STAR_6',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

