<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use UnexpectedValueException;

/**
 * Protobuf type <code>kuaishouPubf.WebCommentFeedShowType</code>
 */
class WebCommentFeedShowType
{
    /**
     * Generated from protobuf enum <code>FEED_SHOW_UNKNOWN = 0;</code>
     */
    const FEED_SHOW_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>FEED_SHOW_NORMAL = 1;</code>
     */
    const FEED_SHOW_NORMAL = 1;
    /**
     * Generated from protobuf enum <code>FEED_HIDDEN = 2;</code>
     */
    const FEED_HIDDEN = 2;

    private static $valueToName = [
        self::FEED_SHOW_UNKNOWN => 'FEED_SHOW_UNKNOWN',
        self::FEED_SHOW_NORMAL => 'FEED_SHOW_NORMAL',
        self::FEED_HIDDEN => 'FEED_HIDDEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

