<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kuaishouPubf.WebCommentFeed</code>
 */
class WebCommentFeed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.kuaishouPubf.SimpleUserInfo user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>string deviceHash = 4;</code>
     */
    protected $deviceHash = '';
    /**
     * Generated from protobuf field <code>uint64 sortRank = 5;</code>
     */
    protected $sortRank = 0;
    /**
     * Generated from protobuf field <code>string color = 6;</code>
     */
    protected $color = '';
    /**
     * Generated from protobuf field <code>.kuaishouPubf.WebCommentFeedShowType showType = 7;</code>
     */
    protected $showType = 0;
    /**
     * Generated from protobuf field <code>.kuaishouPubf.LiveAudienceState senderState = 8;</code>
     */
    protected $senderState = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \KuaishouPubf\SimpleUserInfo $user
     *     @type string $content
     *     @type string $deviceHash
     *     @type int|string $sortRank
     *     @type string $color
     *     @type int $showType
     *     @type \KuaishouPubf\LiveAudienceState $senderState
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.SimpleUserInfo user = 2;</code>
     * @return \KuaishouPubf\SimpleUserInfo|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.SimpleUserInfo user = 2;</code>
     * @param \KuaishouPubf\SimpleUserInfo $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \KuaishouPubf\SimpleUserInfo::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deviceHash = 4;</code>
     * @return string
     */
    public function getDeviceHash()
    {
        return $this->deviceHash;
    }

    /**
     * Generated from protobuf field <code>string deviceHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sortRank = 5;</code>
     * @return int|string
     */
    public function getSortRank()
    {
        return $this->sortRank;
    }

    /**
     * Generated from protobuf field <code>uint64 sortRank = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSortRank($var)
    {
        GPBUtil::checkUint64($var);
        $this->sortRank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string color = 6;</code>
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>string color = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.WebCommentFeedShowType showType = 7;</code>
     * @return int
     */
    public function getShowType()
    {
        return $this->showType;
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.WebCommentFeedShowType showType = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setShowType($var)
    {
        GPBUtil::checkEnum($var, \KuaishouPubf\WebCommentFeedShowType::class);
        $this->showType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.LiveAudienceState senderState = 8;</code>
     * @return \KuaishouPubf\LiveAudienceState|null
     */
    public function getSenderState()
    {
        return $this->senderState;
    }

    public function hasSenderState()
    {
        return isset($this->senderState);
    }

    public function clearSenderState()
    {
        unset($this->senderState);
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.LiveAudienceState senderState = 8;</code>
     * @param \KuaishouPubf\LiveAudienceState $var
     * @return $this
     */
    public function setSenderState($var)
    {
        GPBUtil::checkMessage($var, \KuaishouPubf\LiveAudienceState::class);
        $this->senderState = $var;

        return $this;
    }

}

