<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use UnexpectedValueException;

/**
 * Protobuf type <code>kuaishouPubf.WebLiveAssistantType</code>
 */
class WebLiveAssistantType
{
    /**
     * Generated from protobuf enum <code>WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE = 0;</code>
     */
    const WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE = 0;
    /**
     * Generated from protobuf enum <code>SUPER = 1;</code>
     */
    const SUPER = 1;
    /**
     * Generated from protobuf enum <code>JUNIOR = 2;</code>
     */
    const JUNIOR = 2;

    private static $valueToName = [
        self::WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE => 'WEB_LIVE_ASSISTANT_TYPE_UNKNOWN_ASSISTANT_TYPE',
        self::SUPER => 'SUPER',
        self::JUNIOR => 'JUNIOR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

