<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ks.proto

namespace KuaishouPubf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kuaishouPubf.WebLikeFeed</code>
 */
class WebLikeFeed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.kuaishouPubf.SimpleUserInfo user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>uint64 sortRank = 3;</code>
     */
    protected $sortRank = 0;
    /**
     * Generated from protobuf field <code>string deviceHash = 4;</code>
     */
    protected $deviceHash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \KuaishouPubf\SimpleUserInfo $user
     *     @type int|string $sortRank
     *     @type string $deviceHash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ks::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.SimpleUserInfo user = 2;</code>
     * @return \KuaishouPubf\SimpleUserInfo|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.kuaishouPubf.SimpleUserInfo user = 2;</code>
     * @param \KuaishouPubf\SimpleUserInfo $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \KuaishouPubf\SimpleUserInfo::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sortRank = 3;</code>
     * @return int|string
     */
    public function getSortRank()
    {
        return $this->sortRank;
    }

    /**
     * Generated from protobuf field <code>uint64 sortRank = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSortRank($var)
    {
        GPBUtil::checkUint64($var);
        $this->sortRank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deviceHash = 4;</code>
     * @return string
     */
    public function getDeviceHash()
    {
        return $this->deviceHash;
    }

    /**
     * Generated from protobuf field <code>string deviceHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceHash = $var;

        return $this;
    }

}

